/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CategoriesSteepIdImport } from './routes/categories/$steepId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesSteepIdRoute = CategoriesSteepIdImport.update({
  id: '/categories/$steepId',
  path: '/categories/$steepId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/categories/$steepId': {
      id: '/categories/$steepId'
      path: '/categories/$steepId'
      fullPath: '/categories/$steepId'
      preLoaderRoute: typeof CategoriesSteepIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$steepId': typeof CategoriesSteepIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$steepId': typeof CategoriesSteepIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/categories/$steepId': typeof CategoriesSteepIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories/$steepId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories/$steepId'
  id: '__root__' | '/' | '/categories/$steepId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesSteepIdRoute: typeof CategoriesSteepIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesSteepIdRoute: CategoriesSteepIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/categories/$steepId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/categories/$steepId": {
      "filePath": "categories/$steepId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
